"use client";
import { useEffect } from "react";
import Image from "next/image";
import Head from "next/head";
import {
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
  AiOutlineMail,
} from "react-icons/ai";
import useDarkMode from "@/components/darkmode";
import Header from "@/components/header";
import Timeline from "@/components/timeline";

export default function Home() {
  const { darkMode } = useDarkMode();
  // This ensures that the component re-renders when darkMode changes
  useEffect(() => {
    // This forces a re-render when darkMode changes
    console.log("something changed");
  }, [darkMode]);

  return (
    <div
      className={`font-nexa ${darkMode ? "dark" : ""} ${
        darkMode ? "text-white" : "text-slate-700"
      }`}
    >
      <Head>
        <title>Brian Li's Portfolio</title>
        <meta name="description" content="Generated by ajdsfkk"></meta>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </Head>

      <main className="bg-white px-10 dark:bg-slate-700">
        <section className="min-h-screen">
          <Header />
          <div className="flex">
            <div className="ml-10">
              <div className="inline-block max-w-[520px] max-h-[667px] relative overflow-hidden ">
                <Image
                  src={"/websitepic2.jpg"}
                  width={520}
                  height={500}
                  className="object-cover transition-all duration-300 transform hover:scale-110"
                />
              </div>
              <div className="text-5xl flex justify-start gap-28 py-10 text-slate-700">
                <a
                  href="https://github.com/BrianLi23"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillGithub />
                </a>

                <a
                  href="https://www.linkedin.com/in/brian-li2028/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillLinkedin />
                </a>

                <a
                  href="mailto:b77li@uwaterloo.ca"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiOutlineMail />
                </a>

                <a
                  href="https://www.instagram.com/brixn.li/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <AiFillInstagram />
                </a>
              </div>
            </div>
            <div className="pl-64">
              <h2 className="text-5xl py-2">Brian Li</h2>
              <h3 className="text-2xl py-2">Developer, Student, Learner</h3>
              <p
                className="text-xl py-2 leading-loose "
                style={{ maxWidth: "600px" }}
              >
                Hello, my name is Brian Li, a first year Computer Engineering
                student at the University of Waterloo. My passions lie in AI
                development and firmware tinkering; I'm keen on connectiing with
                others and learning new things.
              </p>
            </div>
          </div>
        </section>
        <Timeline />
      </main>
    </div>
  );
}
