"use client";
import Image from "next/image";
import styles from "./page.module.css";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import {
  AiFillGithub,
  AiFillInstagram,
  AiFillLinkedin,
  AiOutlineMail,
} from "react-icons/ai";

import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setDarkMode(!darkMode);
  };

  return (
    /* */
    <div className={`font-nexa ${darkMode ? "dark" : ""}`}>
      <Head>
        <title>Brian Li's Portfolio</title>
        <meta name="description" content="Generated by ajdsfkk"></meta>
        <link rel="icon" herf="/favicon.ico" sizes="any" />
      </Head>

      <main className="bg-white px-10 dark:bg-slate-700">
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between">
            <Image src={"/websitelogo.png"} width={200} height={200} />
            <ul className="font-nexa flex items-center">
              <button onClick={toggleDarkMode}>
                {darkMode ? (
                  <BsFillSunFill
                    className="cursor-pointer text-2xl relative mb-20"
                    color="white"
                  />
                ) : (
                  <BsFillMoonStarsFill
                    className="cursor-pointer text-2xl relative mb-20"
                    color="rgb(51,65,85)"
                  />
                )}
              </button>
              <li className="relative mb-20">
                <a
                  className="bg-gradient-to-r from-slate-300 to-slate-400 text-white px-4 py-2 rounded-md ml-8"
                  href="/BrianLiResume.pdf"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex">
            <span className="relative max-w-xl overflow-hidden ml-10 ">
              <Image
                src={"/websitepic2.jpg"}
                width={500}
                height={500}
                className="w-full h-full object-cover transition-all duration-300 transform hover:scale-110"
              />
              <div className="absolute bottom-0 left-0 w-full h-2 bg-blue-500 opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
            </span>
            <span className="pl-64">
              <h2 className="text-5xl py-2 text-slate-700">Brian Li</h2>
              <h3 className="text-2xl py-2">Developer, Student, Learner</h3>
              <p></p>
            </span>
          </div>
          <div className="ml-10 ">
            <div className="text-5xl flex justify-start gap-16 py-10 text-slate-700">
              <a
                href="https://github.com/BrianLi23"
                target="_blank"
                rel="noopener noreferrer"
                className="px-2"
              >
                <AiFillGithub />
              </a>

              <a
                href="https://www.linkedin.com/in/brian-li2028/"
                target="_blank"
                rel="noopener noreferrer"
                className="px-10"
              >
                <AiFillLinkedin />
              </a>

              <a
                href="mailto:b77li@uwaterloo.ca"
                target="_blank"
                rel="noopener noreferrer"
                className="pr-10"
              >
                <AiOutlineMail />
              </a>

              <a
                href="https://www.instagram.com/brixn.li/"
                target="_blank"
                rel="noopener noreferrer"
              >
                <AiFillInstagram />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
